### ISSUE TITLE
Actualizar elenco de profesores

### ISSUE THREAD

**Issue by sepu85** [daoeducation/site#6]
Hola, para el primero curso hay otros dos profesores que formarán parte, por favor añadirlos a la página:
- Pol Bordas: https://hackmd.io/ok_2YQJ0T2qWtEBTbMZKGA
- Alex Viñas: https://hackmd.io/I-v3uY9_QRSyA1kDqlq_kw

los datos ya estan en formato de la plantilla, @bronxi47 si puedes añadirlos porfa!

**Comment by bronxi47** [comment]
Claro, Gus @sepu85 . Agregué a Alex, pero en el link de Pol veo solo su Bio y ningún dato más.
¿Está bien el orden en la página de presentación de profesores? Sino se puede modificar su posición cambiando el número en "order_in_about: 90" de su .md.

**Comment by sepu85** [comment]
hola @bronxi47 , ahi estan todos los datos de Pol, solo que veo que tengo algo mal con el formato de la fiha (as usual me pierdo con el template y el markdown) asi que te los dejo aqui abajo:

```
---
layout: profesor
title: "Pol Bordas"
description: La Tecnología al servicio del desarrollo. Dedicado al empoderamiento digital.
img: "pol_bordas.jpg"
nationality: "Español"
position: "BizDev Comms&Marketing "
order_in_about: 40

# Comentar las que no apliquen, colocar el handle según corresponda.
linkedin: polbordasbaches
#instagram:
twitter_user: Pol_Lanski
#facebook: 
#github_username:

articles:
  - name: "Better Than Free? The End of FAANG"
    link: https://www.youtube.com/watch?v=mIqONylnLbE&ab_channel=EthereumFoundation
  - name: "An Infrastructure Vision for Web3"
    link: https://medium.com/dappnode/an-infrastructure-vision-for-web3-3074c5c27ba4
  - name: "How Decentralized Giving could have helped (and will help) increase Transparency and avoid Cases like Oxfam’s Scandal"
    link: https://medium.com/giveth/how-decentralized-giving-could-have-helped-and-will-help-increase-transparency-and-avoid-cases-dd2a001a0f2c
 

programs:
  - name: "From Zero to Hero"
    link: from_zero_to_hero

---


¿Cómo podemos utilizar la tecnología para mejorar la vida de las personas y asegurar un futuro mejor? Utilizando esta pregunta como guía, Pol ha guiado su carrera para aumentar el impacto positivo que la tecnología puede tener y mitigar sus externalidades. 
Su proyecto principal es DAppNode, Software Libre y Open Source para acercar las tecnologías descentralizadas a todo el mundo, y és colaborador en Iden3 (Identidad Digital Soberana) y Hermez Network (una solución de escalabilidad blockchain para hacer los servicios financieros descentralizados accesibles a la población desbancarizada). Fundador de Decentral Node y Mundo Descentralizado. 
Antes fue el Jefe de Relaciones Industriales y Responsabilidad Social Corporativa para Amadeus en Asia Pacífico. 
MBA y licenciado en Periodismo.
```
